package com.clipforge.ai.domain.model
data class Transition(val type: TransitionType, val durationMs: Long = 500L, val isPremium: Boolean = false)
enum class TransitionType(val label: String, val isPremium: Boolean) {
    NONE("None", false),
    DISSOLVE("Dissolve", false),
    FADE("Fade", false),
    FADE_BLACK("Fade Black", false),
    FADE_WHITE("Fade White", false),
    SLIDE_LEFT("Slide Left", false),
    SLIDE_RIGHT("Slide Right", false),
    PUSH_LEFT("Push Left", false),
    PUSH_RIGHT("Push Right", false),
    ZOOM_IN("Zoom In", false),
    ZOOM_OUT("Zoom Out", false),
    BLUR("Blur", false),
    MOTION_BLUR("Motion Blur", false),
    MOTION_BLUR_LEFT("Motion Blur Left", false),
    MOTION_BLUR_RIGHT("Motion Blur Right", false),
    MOTION_BLUR_UP("Motion Blur Up", false),
    MOTION_BLUR_DOWN("Motion Blur Down", false),
    GAUSSIAN_BLUR("Gaussian Blur", false),
    SPIN("Spin", false),
    ROTATE("Rotate", false),
    CAMERA_ROLL("Camera Roll", false),
    WHIP_PAN_LEFT("Whip Pan Left", false),
    WHIP_PAN_RIGHT("Whip Pan Right", false),
    WHIP_PAN_UP("Whip Pan Up", false),
    WHIP_PAN_DOWN("Whip Pan Down", false),
    CROSS_DISSOLVE("Dissolve", false),
    FLASH("Flash White", false),
    FLASH_BLACK("Flash Black", false),
    FLASH_WARM("Flash Warm", false),
    FLASH_BLUE("Flash Blue", false),
    FILM_BURN("Film Burn", false),
    FILM_BURN_WARM("Film Burn Warm", false),
    FILM_BURN_HEAVY("Film Burn Heavy", false),
    BOUNCE("Bounce", false),
    SHAKE("Shake", false),
    SWING("Swing", false),
    POP("Pop", false),
    WIPE("Wipe", false),
    WIPE_RIGHT("Wipe Right", false),
    SLIDE_UP("Slide Up", false),
    SLIDE_DOWN("Slide Down", false),
    PUSH_UP("Push Up", false),
    PUSH_DOWN("Push Down", false),
    WIPE_UP("Wipe Up", false),
    WIPE_DOWN("Wipe Down", false),
    MIRROR_FLIP("Mirror Flip", false),
    GLITCH("Glitch", false),
    GLITCH_PRO("Glitch Pro", false),
    GLITCH_DIGITAL("Glitch Digital", false),
    GLITCH_RGB("Glitch RGB", false),
    GLITCH_SCANLINE("Glitch Scanline", false),
    RGB_SPLIT("RGB Split", false),
    CHROMATIC_ABERRATION("Chromatic Aberration", false),
    CUBE_LEFT("3D Cube Left", false),
    CUBE_RIGHT("3D Cube Right", false),
    CUBE_UP("3D Cube Up", false),
    CUBE_DOWN("3D Cube Down", false),
    FLIP_LEFT("Flip Left", false),
    FLIP_RIGHT("Flip Right", false),
    FLIP_UP("Flip Up", false),
    FLIP_DOWN("Flip Down", false),
    FLIP_HORIZONTAL("3D Flip Horizontal", false),
    FLIP_VERTICAL("3D Flip Vertical", false),
    DOOR_OPEN("3D Door Open", false),
    DOOR_CLOSE("3D Door Close", false),
    CAROUSEL("3D Carousel", false),
    BOOK_TURN("3D Book Turn", false),
    PAGE_TURN("3D Page Turn", false),
    PAGE_TURN_LEFT("Page Turn Left", false),
    PAGE_TURN_RIGHT("Page Turn Right", false),
    PAGE_TURN_UP("Page Turn Up", false),
    PAGE_TURN_DOWN("Page Turn Down", false),
    FOLD("3D Fold", false),
    TUNNEL("3D Tunnel", false),
    PRISM("3D Prism", false)
}
