package com.clipforge.ai.core.animation

object AnimationPresetIds {
    const val FADE_IN = "fade_in"
    const val ZOOM_IN = "zoom_in"
    const val SLIDE_IN_LEFT = "slide_in_left"
    const val SLIDE_IN_RIGHT = "slide_in_right"
    const val SLIDE_IN_UP = "slide_in_up"
    const val SLIDE_IN_DOWN = "slide_in_down"
    const val ROTATE_IN = "rotate_in"
    const val POP_IN = "pop_in"
    const val BOUNCE_IN = "bounce_in"
    const val FADE_OUT = "fade_out"
    const val ZOOM_OUT = "zoom_out"
    const val SLIDE_OUT_RIGHT = "slide_out_right"
    const val SLIDE_OUT_LEFT = "slide_out_left"
    const val SLIDE_OUT_UP = "slide_out_up"
    const val SLIDE_OUT_DOWN = "slide_out_down"
    const val ROTATE_OUT = "rotate_out"
    const val POP_OUT = "pop_out"
    const val BOUNCE_OUT = "bounce_out"
    const val SLOW_ZOOM = "slow_zoom"
    const val PULSE = "pulse"
    const val SWAY = "sway"
    const val FLOAT = "float"
    const val BOB = "bob"
    const val WOBBLE = "wobble"
    const val HEARTBEAT = "heartbeat"
    const val BREATHE = "breathe"
    const val SHAKE_LIGHT = "shake_light"
    const val DRIFT_ZOOM = "drift_zoom"
}
